<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="159" started-at="2019-05-15T16:04:30Z" finished-at="2019-05-15T16:04:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="159" started-at="2019-05-15T16:04:30Z" finished-at="2019-05-15T16:04:31Z">
      <class name="testNgDemo.DemoTest1">
        <test-method status="FAIL" signature="TestTwo()[pri:0, instance:testNgDemo.DemoTest1@5d3411d]" name="TestTwo" duration-ms="109" started-at="2019-05-15T21:34:30Z" finished-at="2019-05-15T21:34:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNgDemo.DemoTest1.TestTwo(DemoTest1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestTwo -->
        <test-method status="PASS" signature="TestOne()[pri:0, instance:testNgDemo.DemoTest1@5d3411d]" name="TestOne" duration-ms="4" started-at="2019-05-15T21:34:31Z" finished-at="2019-05-15T21:34:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestOne -->
        <test-method status="SKIP" signature="TestThird()[pri:0, instance:testNgDemo.DemoTest1@5d3411d]" name="TestThird" duration-ms="2" started-at="2019-05-15T21:34:31Z" depends-on-methods="testNgDemo.DemoTest1.TestTwo" finished-at="2019-05-15T21:34:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestThird -->
      </class> <!-- testNgDemo.DemoTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
